### ISSUE TITLE
Does this setting also support catalina?

### ISSUE THREAD

**Issue by Zardinality** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#24]
Since the macOS 10.15 is out now, I am wondering whether this repo will continue to work on the newest version of macOS. It would be nice if anyone can report the usability. Thanks.

**Comment by Zardinality** [comment]
@tomaculum Hi, I tried to boot the installer(downloaded from my current mojave system) with an external drive whose efi partition is exactly the one in `release 3.0`, with the `-lilubetaall` appended to startup option. However I got `++++++++++++++++` with the verbose option when I tried to boot into the installer. Do you have any idea about this? Or is your `driver` folder in efi partition intact from what is released? Thanks!

**Comment by tomaculum** [comment]
In my case I replaced the whole CLOVER folder on my main EFI partition and I did use the newer release `3.1`.

And I've added the `-lilubetaall` flag to the `config.plist` in the CLOVER folder but that's the only change I've made to the EFI files.

![picture](https://user-images.githubusercontent.com/16617007/66714099-a0d84380-edb2-11e9-9b0a-8c4c3eb23fcc.png)

> However I got ++++++++++++++++ with the verbose option

Do you mean the `This system was automatically rebooted after panic` message?

If yes, I got the same message without the `-lilubetaall` flag and maybe the edit of the config file does the trick as it did for me. 

Note: I did the update through the system preference in Mojave without an external install medium and didn't do a fresh install of macOS. After the installer in Mojave tells you to reboot, select the `install macOS partition` as long as it appears in your partition list.

**Comment by Zardinality** [comment]
Thanks for the comments! It is very helpful of you. I did exactly what you have described but found the clover can't detect my MacOS installation when startup, with the setting in release `3.1`. All I can see in the clover startup interface is my windows and linux installation. I suspect this is because the driver for apfs is malfunctioned(I am using an SSD), but after a few tries there leaves me with no luck. If anyone happens to have the same issue, please let me know!

**Comment by tomaculum** [comment]
I’m sorry this did not work. I am using a ssd as well, this should not be the problem I guess.
@jsassu20 do you have an idea what could cause this issue?

**Comment by rogelin** [comment]
Updating Clover to v5070 + "-lilubetaall" flag, then updating to Catalina via system settings worked for me. 
Before that, I did a clone of my SSD and tried to update without success.

**Comment by Zardinality** [comment]
@rogelin @tomaculum Thanks guys, I have already got Catalina installed. The key is to upgrade the Clover to the newest stable version and add the flag. And I use the `3.1` release.  A few tips I found useful during installation:
1. When updating Clover, my Clover configurator can not find the EFI partition I mount. So I have to download the Clover image and manually copy the `bootx64.efi` and `Cloverx64.efi` to my EFI partition. The image link is there:[click me](https://sourceforge.net/projects/cloverefiboot/files/Bootable_ISO/).
2. My usb wifi dongle driver failed to install after I updated, so anyone wants to try Catalina, please don't forget the compatibility is really a painful issue in 10.15. Finally, I use the driver in [this repo](https://github.com/chris1111/Wireless-USB-Adapter-Clover) and it works with my dongle fine so far.

I will keep this issue open for a while in case anyone wonders the Catalina compatibility issue.

**Comment by sam-anam1** [comment]
hello everyone thank you all for info. 
@Zardinality can you please share your update clover ver. 5070/5071 files? just CLOVERX64.efi and drivers folder please

**Comment by Zardinality** [comment]
@sam-anam1 Here you go: [click me](https://drive.google.com/file/d/1VrtWMrGaOuw8Iyxes2mdjcEwBcaQQ7DH/view?usp=sharing).
This is basically `3.1` release, with only a few diffes as below:
```
⋊> /V/E/E/CLOVER on master ⨯ git diff                                    
diff --git a/ACPI/patched/SSDT-VPS2.aml b/ACPI/patched/SSDT-VPS2.aml
index b0d8262..2e9f943 100644
Binary files a/ACPI/patched/SSDT-VPS2.aml and b/ACPI/patched/SSDT-VPS2.aml differ
diff --git a/CLOVERX64.efi b/CLOVERX64.efi
index cb84f9d..9be1a89 100755
Binary files a/CLOVERX64.efi and b/CLOVERX64.efi differ
diff --git a/config.plist b/config.plist
index 91f2cf1..4d0d02d 100755
--- a/config.plist
+++ b/config.plist
@@ -656,7 +656,7 @@
                <key>#DefaultVolume</key>
                <string>LastBootedVolume</string>
                <key>Arguments</key>
-               <string>kext-dev-mode=1 dart=0 nv_disable=1 -cdfon</string>
+               <string>kext-dev-mode=1 dart=0 nv_disable=1 -cdfon -lilubetaall</string>
                <key>HibernationFixup</key>
                <false/>
                <key>Legacy</key>
```

**Comment by tomaculum** [comment]
There is a new version of [Lilu.kext](https://github.com/acidanthera/Lilu/releases) available which does not need that extra flag

**Comment by Zardinality** [comment]
Weird enough the new `Lilu.kext` doesn't work on me, even with the flag. I would probably just stay for the old ver with the flag.

**Comment by tomaculum** [comment]
I've replaced some other .kext files from his repositories as well, probably there is some kind of dependency between some of those files. But yes, I guess it is the better option to stay on the older version with the flag rather than updating without knowing if it really does everything as it should do.

Maybe someone who knows more about the configs of .kext files could create a pull request or hopefully @jsassu20 updates the repo to work without modifications with Catalina soon.

**Comment by jsassu20** [comment]
Yes it should work just fine, update the kexts though. Im currently in Catalina as we speak...

![Screen Shot 2019-10-20 at 2 00 19 PM](https://user-images.githubusercontent.com/12767985/67163855-21162000-f342-11e9-973b-6fb7ec73931c.png)

**Comment by recmess** [comment]
> Yes it should work just fine, update the kexts though. Im currently in Catalina as we speak...
> 
> ![Screen Shot 2019-10-20 at 2 00 19 PM](https://user-images.githubusercontent.com/12767985/67163855-21162000-f342-11e9-973b-6fb7ec73931c.png)
INTEL HD 6000?

**Comment by jsassu20** [comment]
just officially added support for Catalina as well as updated the repo
