### ISSUE TITLE
T450s VGA don't work

### ISSUE THREAD

**Issue by truonghdpk** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#30]
Thanks your configuration macos is the best, i'm trying connect another screen but it don't work. Any one have idea please?

**Comment by truonghdpk** [comment]
In my device track pad, touchpad, sound, usb is working

**Comment by truonghdpk** [comment]
Anyone have same?

**Comment by truonghdpk** [comment]
anyone try mini display port

**Comment by truonghdpk** [comment]
I tried just in mine copy your repo in my CLOVER forder and it work to some hardware

**Comment by jsassu20** [comment]
VGA doesn't work, Mac doesn't support VGA so there are no VGA drivers. Your best bet is to use a Mini display adapter to connect via HDMI. Sorry theres nothing I can do about this, its mentioned in the info portion on the main page.
