### ISSUE TITLE
Not detecting ethernet connection, can't install due to lack of connectivity

### ISSUE THREAD

**Issue by LewisLarsen** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#37]
Hi,

The installer is working but unfortunately I can't proceed to install the OS, it says an internet connection is required, but my ethernet cable is definitely plugged in. 

Could I potentially be missing a driver? I do believe that I have transferred the files correctly since it did launch the install utility, I just can't progress due to this lack of internet connectivity. 

The ethernet cable is definitely plugged in and I have restarted the laptop a couple of times, to no avail. Do you have any suggestions?

Thanks,
Lewis

**Comment by LewisLarsen** [comment]
I dropped the IntelMausiEthernet Kext into the relevant folders in the hopes that it would find it, unfortunately not. 

The next step is for me to try upgrading my BIOS, as I'm not on the latest version, although truthfully I don't know how much impact the update will have on getting ethernet detected. 

Just as a confirmation, I downloaded the latest release of your package and dropped it into my USB stick and altered my BIOS settings accordingly. It _should_ be working and ethernet should be picked up, but unfortunately that isn't the case.

**Comment by jsassu20** [comment]
It sounds like you're in the recovery partition and not in the clover installer. In order for recovery to run properly it requires that you installed kexts to the system prior to having to use recovery. Try booting directly from boot manager into your usb

**Comment by LewisLarsen** [comment]
I did finally solve it!

Clover 5096 for whatever reason wasn't seeing my ethernet connection, I downgraded to 5092 and I was able to install Catalina with no issues. 

Thanks for the help. :)

**Comment by jsassu20** [comment]
Try acid anthers Intelmausi kext
