### ISSUE TITLE
External hard drives aren't recognized

### ISSUE THREAD

**Issue by AgentHV** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#38]
My external USB-hard drive is formatted with exFat and should be supported by macOS. However, it doesn't appear. It isn't recognized in any way, it shows up nowhere. Could this be a ACPI-problem?
EDIT: It has to be said, that I use a T450s I5, so the problem isn't me not patching anything I should because I'm lazy or something.

**Comment by jsassu20** [comment]
try adding the fat driver into clovers uefi drivers folder. This can be accomplished using clover installer.

**Comment by AgentHV** [comment]
I tried this, but I have still the same problem. It won't recognize my iPhone too. May it be something with the USB ports in general? It didn't recognize or charge my iPhone too, unless the power delivery port which charges everything. May it be it possible that some of the patches don't work on a T450s?

**Comment by jsassu20** [comment]
Glad to hear its fixed! Happy holidays everyone.
